### ISSUE TITLE
Remove sudo requirement to install CLI

### ISSUE THREAD

**Issue by xvasi** [openline-ai/openline-cli#116]
We should not force use of sudo to be able to install our CLI.

**Comment by edifirut** [comment]
i think this is happening because i've installed npm as a sudo user

efirut@Firuts-MacBook-Pro openline-contacts % npm install -g openline
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/openline
npm ERR! dest /usr/local/lib/node_modules/.openline-odQsQbRI
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/openline' -> '/usr/local/lib/node_modules/.openline-odQsQbRI'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/openline' -> '/usr/local/lib/node_modules/.openline-odQsQbRI']



efirut@Firuts-MacBook-Pro openline-contacts % ls -l /usr/local/lib/node_modules
total 0
drwxr-xr-x   7 root  wheel  224 Jul  7 15:27 corepack
drwxr-xr-x  12 root  wheel  384 Jul  7 15:27 npm
drwxr-xr-x   9 root  wheel  288 Dec  2 10:56 openline
drwxr-xr-x   8 root  wheel  256 Aug  3 15:44 yarn

**Comment by mattbr0wn** [comment]
Sudo no longer required if you use `brew` for mac.  

Sudo still required if you use install script
